Rbn 40 create and fit footer
ProductDock/rbc3-library-fe pull request #17
Opened 2024-10-03 08:25 UTC by maxencije

### What did you implement?

Footer component is implemented, fully responsive.

### How can we verify the changes?

### More info

- Jira: [RBN-40](https://productdock.atlassian.net/browse/RBN-40)

- Figma: [Design](https://www.figma.com/design/x4SgW80BE24s9gAFHM3gXS/RBC---Novi-Sad%2C-2024?node-id=2597-13715&t=zQZFMBZ56c1sxpri-4)

2024-10-03 11:13 UTC, ssukovic requested changes

2024-10-03 11:13 UTC, ssukovic commented on src/components/Footer/BackToTop.tsx
> +    window.scroll(0, 0)
Add `smooth` behaviour to scroll, so it's not so harsh. See how [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll).

2024-10-03 11:13 UTC, ssukovic commented on src/assets/footerLogo.svg
Remove one of the stamp svgs

2024-10-03 11:13 UTC, ssukovic commented on src/assets/arrow.png
Export this icon as svg from figma for better quality. SVG images are vector based which allows resizing without losing quality. This is how it looks like now: 
<img width="276" alt="Screenshot 2024-10-03 at 12 59 52" src="https://github.com/user-attachments/assets/9e1d78b7-da54-446c-a2db-3b19b98f76b1">

2024-10-04 11:26 UTC, ssukovic submitted a review, later dismissed
🚀

2024-10-04 11:29 UTC, Aleksandra-Romanic submitted a review, later dismissed

2024-10-04 13:51 UTC, ssukovic approved these changes

2024-10-07 06:59 UTC, isidora-b approved these changes

2024-10-07 07:00 UTC, merged