Created book component for carousel
ProductDock/rbc3-library-fe pull request #18
Opened 2024-10-04 07:23 UTC by maxencije

### What did you implement?

Created book card component for carousel.

### How can we verify the changes?

### More info

- Jira: [RBN-44](https://productdock.atlassian.net/browse/RBN-44)

- Figma: [Design](https://www.figma.com/design/x4SgW80BE24s9gAFHM3gXS/RBC---Novi-Sad%2C-2024?node-id=2134-1466&node-type=frame&t=SeYhScd7umDgUsl6-0)

2024-10-04 08:25 UTC, ssukovic requested changes

2024-10-04 08:25 UTC, ssukovic commented on src/components/BookCard/BookCard.tsx
Add index.ts file to this folder and update BookCard import in Homepage file

2024-10-04 08:25 UTC, ssukovic commented on src/components/BookCard/BookCard.tsx
> +        <div className={styles.favorite}>
Create a separate component for this, with one boolean prop that indicates whether the book is in favourites:
`<Favorite inFavorites=true/>` - returns component with filled in heart

You can pass this prop to BookCard component too, so in Homepage component you would have for example:

```
<BookCard inFavorites={true} /> - this book has filled in card
<BookCard inFavorites={false} /> - this book has empty heart
```

2024-10-04 10:51 UTC, ssukovic requested changes

2024-10-04 10:51 UTC, ssukovic commented on src/components/BookCard/BookCard.tsx
> +          <div className={styles.line}></div>
You can use material's [divider](https://mui.com/material-ui/react-divider/) here instead of the line

2024-10-04 10:51 UTC, ssukovic commented on src/components/BookCard/BookCard.tsx
> +    <div className={styles.bookCard}>
Set the same width as in Figma for the Card component from the Catalog, the cards from the Popular section are wider

2024-10-04 11:18 UTC, ssukovic commented on src/components/BookCard/BookCard.module.css
You can remove all z-indexes in this file, they don't do anything here

2024-10-07 07:26 UTC, Aleksandra-Romanic submitted a review, later dismissed

2024-10-07 11:36 UTC, ssukovic commented on src/pages/Homepage/Homepage.tsx
> +        style={{
Move this styling to Homepage.module.css to keep all styling consistent
Also for the sake of consistency, convert those 10rem to pixels

2024-10-07 11:36 UTC, ssukovic submitted a review, later dismissed

2024-10-08 13:00 UTC, ssukovic commented on src/components/BookCard/BookCard.module.css
> +  width: 400px;
Decrease this width the match the design of catalogue book card component from [figma](https://www.figma.com/design/x4SgW80BE24s9gAFHM3gXS/RBC---Novi-Sad%2C-2024?node-id=2134-1466&node-type=frame&t=1feQzPRTDtI0a8pt-0)

2024-10-08 13:51 UTC, ssukovic requested changes

2024-10-08 13:51 UTC, ssukovic commented on src/pages/Homepage/BookCatalogueSection/BookCatalogueSection.module.css
> +  gap: 10rem;
```suggestion
  row-gap: 120px;
  column-gap: 40px;
```
This gap should be the same as in Figma for catalogue section.

2024-10-08 13:51 UTC, ssukovic commented on src/components/BookCard/BookCard.module.css
> +  text-decoration: underline;
You should add a top margin here for author name, so it matches Figma
<img width="250" alt="Screenshot 2024-10-08 at 15 50 48" src="https://github.com/user-attachments/assets/6b6cc087-001f-4bc5-a58b-a88ff6457bf0">

2024-10-09 08:24 UTC, ssukovic approved these changes

2024-10-09 08:39 UTC, isidora-b approved these changes

2024-10-09 08:43 UTC, merged